name: Android Native Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    environment: staging
    name: Install and build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11.0.18"

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
   
      - name: Generate and load .env file
        run: |
          printenv | grep "RN" >> .env.${{ secrets.ENVIRONMENT }}
          export $(cat .env.${{ secrets.ENVIRONMENT }} | xargs)
          echo $(cat .env.${{ secrets.ENVIRONMENT }})
        env:
          RN_API_URL: ${{ secrets.RN_API_URL }}
          RN_EAS_PROJECT_ID: ${{ secrets.RN_EAS_PROJECT_ID }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
  
      - name: Restore Project Dependencies (node_modules)
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Install dependencies
        env:
          APP_ENV: ${{ secrets.ENVIRONMENT }}
        run: yarn install --immutable

      - name: Running expo prebuild
        env:
          APP_ENV: ${{ secrets.ENVIRONMENT }}
        run: yarn prebuild -p android
      
      - name: Running expo fix
        run: npx expo install --fix
      
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App APK
        run: |
          cd android && ./gradlew assembleRelease
      
      # ## sign generated apk
      # - name: Sign APK
      #   id: sign_app
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: android/app/build/outputs/apk/release/
      #     signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
      #     alias: ${{ secrets.ANDROID_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
